#!/bin/bash

SBDS_CMD = "$(which sbds)"

exec setuidgid nobody python3.6 "${SBDS_CMD}" server serve \
  --database_url "${DATABASE_URL}" \
  --host "${HTTP_HOST:-0.0.0.0}" \
  --port "${HTTP_PORT:-9000}"
