# -*- coding: utf-8 -*-
from sqlalchemy.types import Enum

operation_types_enum = Enum(
    'account_create',
    'account_update',
    'account_witness_proxy',
    'account_witness_vote',
    'author_reward_operation',
    'cancel_transfer_from_savings',
    'challenge_authority',
    'change_recovery_account',
    'comment',
    'comment_benefactor_reward_operation',
    'comment_options',
    'comment_payout_update_operation',
    'comment_reward_operation',
    'convert',
    'curation_reward_operation',
    'custom',
    'custom_binary_operation',
    'custom_json',
    'decline_voting_rights_operation',
    'delete_comment',
    'escrow_approve',
    'escrow_dispute',
    'escrow_release',
    'escrow_transfer',
    'feed_publish',
    'fill_convert_request_operation',
    'fill_order_operation',
    'fill_transfer_from_savings_operation',
    'fill_vesting_withdraw_operation',
    'hardfork_operation',
    'interest_operation',
    'limit_order_cancel',
    'limit_order_create',
    'limit_order_create2',
    'liquidity_reward_operation',
    'pow',
    'pow2',
    'producer_reward_operation',
    'prove_authority',
    'recover_account',
    'report_over_production',
    'request_account_recovery',
    'reset_account_operation',
    'return_vesting_delegation_operation',
    'set_reset_account_operation',
    'set_withdraw_vesting_route',
    'shutdown_witness_operation',
    'transfer',
    'transfer_from_savings',
    'transfer_to_savings',
    'transfer_to_vesting',
    'vote',
    'withdraw_vesting',
    'witness_update',
    name='sbds_transaction_types')

comment_types_enum = Enum('post', 'comment', name='sbds_comment_types')

extraction_source_enum = Enum('body', 'meta', name='sbds_extraction_sources')
