# -*- coding: utf-8 -*-

CREATE_BLOCK_RULES = [
    'CREATE OR REPLACE RULE rule_update_block AS ON UPDATE TO sbds_core_blocks DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_block AS ON DELETE TO sbds_core_blocks DO INSTEAD NOTHING;',
]

CREATE_OP_RULES = [
    'CREATE OR REPLACE RULE rule_update_sbds_op_account_creates AS ON UPDATE TO sbds_op_account_creates DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_account_creates AS ON DELETE TO sbds_op_account_creates DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_account_create_with_delegations AS ON UPDATE TO sbds_op_account_create_with_delegations DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_account_create_with_delegations AS ON DELETE TO sbds_op_account_create_with_delegations DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_account_updates AS ON UPDATE TO sbds_op_account_updates DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_account_updates AS ON DELETE TO sbds_op_account_updates DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_comments AS ON UPDATE TO sbds_op_comments DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_comments AS ON DELETE TO sbds_op_comments DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_comment_option AS ON UPDATE TO sbds_op_comment_option DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_comment_option AS ON DELETE TO sbds_op_comment_option DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_challenge_authorities AS ON UPDATE TO sbds_op_challenge_authorities DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_challenge_authorities AS ON DELETE TO sbds_op_challenge_authorities DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_prove_authorities AS ON UPDATE TO sbds_op_prove_authorities DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_prove_authorities AS ON DELETE TO sbds_op_prove_authorities DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_delete_comments AS ON UPDATE TO sbds_op_delete_comments DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_delete_comments AS ON DELETE TO sbds_op_delete_comments DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_votes AS ON UPDATE TO sbds_op_votes DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_votes AS ON DELETE TO sbds_op_votes DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_transfers AS ON UPDATE TO sbds_op_transfers DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_transfers AS ON DELETE TO sbds_op_transfers DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_escrow_transfers AS ON UPDATE TO sbds_op_escrow_transfers DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_escrow_transfers AS ON DELETE TO sbds_op_escrow_transfers DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_escrow_approves AS ON UPDATE TO sbds_op_escrow_approves DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_escrow_approves AS ON DELETE TO sbds_op_escrow_approves DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_escrow_disputes AS ON UPDATE TO sbds_op_escrow_disputes DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_escrow_disputes AS ON DELETE TO sbds_op_escrow_disputes DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_escrow_releases AS ON UPDATE TO sbds_op_escrow_releases DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_escrow_releases AS ON DELETE TO sbds_op_escrow_releases DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_transfer_to_vestings AS ON UPDATE TO sbds_op_transfer_to_vestings DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_transfer_to_vestings AS ON DELETE TO sbds_op_transfer_to_vestings DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_withdraw_vestings AS ON UPDATE TO sbds_op_withdraw_vestings DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_withdraw_vestings AS ON DELETE TO sbds_op_withdraw_vestings DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_set_withdraw_vesting_routes AS ON UPDATE TO sbds_op_set_withdraw_vesting_routes DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_set_withdraw_vesting_routes AS ON DELETE TO sbds_op_set_withdraw_vesting_routes DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_witness_updates AS ON UPDATE TO sbds_op_witness_updates DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_witness_updates AS ON DELETE TO sbds_op_witness_updates DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_account_witness_votes AS ON UPDATE TO sbds_op_account_witness_votes DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_account_witness_votes AS ON DELETE TO sbds_op_account_witness_votes DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_account_witness_proxies AS ON UPDATE TO sbds_op_account_witness_proxies DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_account_witness_proxies AS ON DELETE TO sbds_op_account_witness_proxies DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_customs AS ON UPDATE TO sbds_op_customs DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_customs AS ON DELETE TO sbds_op_customs DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_custom_jsons AS ON UPDATE TO sbds_op_custom_jsons DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_custom_jsons AS ON DELETE TO sbds_op_custom_jsons DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_custom_binaries AS ON UPDATE TO sbds_op_custom_binaries DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_custom_binaries AS ON DELETE TO sbds_op_custom_binaries DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_feed_publishes AS ON UPDATE TO sbds_op_feed_publishes DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_feed_publishes AS ON DELETE TO sbds_op_feed_publishes DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_converts AS ON UPDATE TO sbds_op_converts DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_converts AS ON DELETE TO sbds_op_converts DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_limit_order_creates AS ON UPDATE TO sbds_op_limit_order_creates DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_limit_order_creates AS ON DELETE TO sbds_op_limit_order_creates DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_limit_order_create2s AS ON UPDATE TO sbds_op_limit_order_create2s DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_limit_order_create2s AS ON DELETE TO sbds_op_limit_order_create2s DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_limit_order_cancels AS ON UPDATE TO sbds_op_limit_order_cancels DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_limit_order_cancels AS ON DELETE TO sbds_op_limit_order_cancels DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_pows AS ON UPDATE TO sbds_op_pows DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_pows AS ON DELETE TO sbds_op_pows DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_pow2s AS ON UPDATE TO sbds_op_pow2s DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_pow2s AS ON DELETE TO sbds_op_pow2s DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_report_over_productions AS ON UPDATE TO sbds_op_report_over_productions DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_report_over_productions AS ON DELETE TO sbds_op_report_over_productions DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_request_account_recoveries AS ON UPDATE TO sbds_op_request_account_recoveries DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_request_account_recoveries AS ON DELETE TO sbds_op_request_account_recoveries DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_recover_accounts AS ON UPDATE TO sbds_op_recover_accounts DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_recover_accounts AS ON DELETE TO sbds_op_recover_accounts DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_reset_accounts AS ON UPDATE TO sbds_op_reset_accounts DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_reset_accounts AS ON DELETE TO sbds_op_reset_accounts DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_set_reset_accounts AS ON UPDATE TO sbds_op_set_reset_accounts DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_set_reset_accounts AS ON DELETE TO sbds_op_set_reset_accounts DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_change_recovery_accounts AS ON UPDATE TO sbds_op_change_recovery_accounts DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_change_recovery_accounts AS ON DELETE TO sbds_op_change_recovery_accounts DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_transfer_to_saving AS ON UPDATE TO sbds_op_transfer_to_saving DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_transfer_to_saving AS ON DELETE TO sbds_op_transfer_to_saving DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_transfer_from_saving AS ON UPDATE TO sbds_op_transfer_from_saving DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_transfer_from_saving AS ON DELETE TO sbds_op_transfer_from_saving DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_cancel_transfer_from_saving AS ON UPDATE TO sbds_op_cancel_transfer_from_saving DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_cancel_transfer_from_saving AS ON DELETE TO sbds_op_cancel_transfer_from_saving DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_decline_voting_right AS ON UPDATE TO sbds_op_decline_voting_right DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_decline_voting_right AS ON DELETE TO sbds_op_decline_voting_right DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_claim_reward_balances AS ON UPDATE TO sbds_op_claim_reward_balances DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_claim_reward_balances AS ON DELETE TO sbds_op_claim_reward_balances DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_delegate_vesting_share AS ON UPDATE TO sbds_op_delegate_vesting_share DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_delegate_vesting_share AS ON DELETE TO sbds_op_delegate_vesting_share DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_virtual_author_rewards AS ON UPDATE TO sbds_op_virtual_author_rewards DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_virtual_author_rewards AS ON DELETE TO sbds_op_virtual_author_rewards DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_virtual_curation_rewards AS ON UPDATE TO sbds_op_virtual_curation_rewards DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_virtual_curation_rewards AS ON DELETE TO sbds_op_virtual_curation_rewards DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_virtual_comment_rewards AS ON UPDATE TO sbds_op_virtual_comment_rewards DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_virtual_comment_rewards AS ON DELETE TO sbds_op_virtual_comment_rewards DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_virtual_liquidity_rewards AS ON UPDATE TO sbds_op_virtual_liquidity_rewards DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_virtual_liquidity_rewards AS ON DELETE TO sbds_op_virtual_liquidity_rewards DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_virtual_interests AS ON UPDATE TO sbds_op_virtual_interests DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_virtual_interests AS ON DELETE TO sbds_op_virtual_interests DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_virtual_fill_convert_requests AS ON UPDATE TO sbds_op_virtual_fill_convert_requests DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_virtual_fill_convert_requests AS ON DELETE TO sbds_op_virtual_fill_convert_requests DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_virtual_fill_vesting_withdraws AS ON UPDATE TO sbds_op_virtual_fill_vesting_withdraws DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_virtual_fill_vesting_withdraws AS ON DELETE TO sbds_op_virtual_fill_vesting_withdraws DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_virtual_shutdown_witnesses AS ON UPDATE TO sbds_op_virtual_shutdown_witnesses DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_virtual_shutdown_witnesses AS ON DELETE TO sbds_op_virtual_shutdown_witnesses DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_virtual_fill_orders AS ON UPDATE TO sbds_op_virtual_fill_orders DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_virtual_fill_orders AS ON DELETE TO sbds_op_virtual_fill_orders DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_virtual_fill_transfer_from_saving AS ON UPDATE TO sbds_op_virtual_fill_transfer_from_saving DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_virtual_fill_transfer_from_saving AS ON DELETE TO sbds_op_virtual_fill_transfer_from_saving DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_virtual_hardforks AS ON UPDATE TO sbds_op_virtual_hardforks DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_virtual_hardforks AS ON DELETE TO sbds_op_virtual_hardforks DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_virtual_comment_payout_updates AS ON UPDATE TO sbds_op_virtual_comment_payout_updates DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_virtual_comment_payout_updates AS ON DELETE TO sbds_op_virtual_comment_payout_updates DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_virtual_return_vesting_delegations AS ON UPDATE TO sbds_op_virtual_return_vesting_delegations DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_virtual_return_vesting_delegations AS ON DELETE TO sbds_op_virtual_return_vesting_delegations DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_virtual_comment_benefactor_rewards AS ON UPDATE TO sbds_op_virtual_comment_benefactor_rewards DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_virtual_comment_benefactor_rewards AS ON DELETE TO sbds_op_virtual_comment_benefactor_rewards DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_update_sbds_op_virtual_producer_rewards AS ON UPDATE TO sbds_op_virtual_producer_rewards DO INSTEAD NOTHING;',
    'CREATE OR REPLACE RULE rule_delete_sbds_op_virtual_producer_rewards AS ON DELETE TO sbds_op_virtual_producer_rewards DO INSTEAD NOTHING;',
]

DROP_BLOCK_RULES = [
    'DROP RULE IF EXISTS rule_update_block ON sbds_core_blocks CASCADE;',
    'DROP RULE IF EXISTS rule_delete_block ON sbds_core_blocks CASCADE;'
]

DROP_OP_RULES = [
    'DROP RULE IF EXISTS rule_update_sbds_op_account_creates ON sbds_op_account_creates CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_account_creates ON sbds_op_account_creates CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_account_create_with_delegations ON sbds_op_account_create_with_delegations CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_account_create_with_delegations ON sbds_op_account_create_with_delegations CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_account_updates ON sbds_op_account_updates CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_account_updates ON sbds_op_account_updates CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_comments ON sbds_op_comments CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_comments ON sbds_op_comments CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_comment_option ON sbds_op_comment_option CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_comment_option ON sbds_op_comment_option CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_challenge_authorities ON sbds_op_challenge_authorities CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_challenge_authorities ON sbds_op_challenge_authorities CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_prove_authorities ON sbds_op_prove_authorities CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_prove_authorities ON sbds_op_prove_authorities CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_delete_comments ON sbds_op_delete_comments CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_delete_comments ON sbds_op_delete_comments CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_votes ON sbds_op_votes CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_votes ON sbds_op_votes CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_transfers ON sbds_op_transfers CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_transfers ON sbds_op_transfers CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_escrow_transfers ON sbds_op_escrow_transfers CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_escrow_transfers ON sbds_op_escrow_transfers CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_escrow_approves ON sbds_op_escrow_approves CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_escrow_approves ON sbds_op_escrow_approves CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_escrow_disputes ON sbds_op_escrow_disputes CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_escrow_disputes ON sbds_op_escrow_disputes CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_escrow_releases ON sbds_op_escrow_releases CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_escrow_releases ON sbds_op_escrow_releases CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_transfer_to_vestings ON sbds_op_transfer_to_vestings CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_transfer_to_vestings ON sbds_op_transfer_to_vestings CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_withdraw_vestings ON sbds_op_withdraw_vestings CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_withdraw_vestings ON sbds_op_withdraw_vestings CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_set_withdraw_vesting_routes ON sbds_op_set_withdraw_vesting_routes CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_set_withdraw_vesting_routes ON sbds_op_set_withdraw_vesting_routes CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_witness_updates ON sbds_op_witness_updates CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_witness_updates ON sbds_op_witness_updates CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_account_witness_votes ON sbds_op_account_witness_votes CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_account_witness_votes ON sbds_op_account_witness_votes CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_account_witness_proxies ON sbds_op_account_witness_proxies CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_account_witness_proxies ON sbds_op_account_witness_proxies CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_customs ON sbds_op_customs CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_customs ON sbds_op_customs CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_custom_jsons ON sbds_op_custom_jsons CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_custom_jsons ON sbds_op_custom_jsons CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_custom_binaries ON sbds_op_custom_binaries CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_custom_binaries ON sbds_op_custom_binaries CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_feed_publishes ON sbds_op_feed_publishes CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_feed_publishes ON sbds_op_feed_publishes CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_converts ON sbds_op_converts CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_converts ON sbds_op_converts CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_limit_order_creates ON sbds_op_limit_order_creates CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_limit_order_creates ON sbds_op_limit_order_creates CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_limit_order_create2s ON sbds_op_limit_order_create2s CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_limit_order_create2s ON sbds_op_limit_order_create2s CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_limit_order_cancels ON sbds_op_limit_order_cancels CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_limit_order_cancels ON sbds_op_limit_order_cancels CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_pows ON sbds_op_pows CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_pows ON sbds_op_pows CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_pow2s ON sbds_op_pow2s CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_pow2s ON sbds_op_pow2s CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_report_over_productions ON sbds_op_report_over_productions CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_report_over_productions ON sbds_op_report_over_productions CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_request_account_recoveries ON sbds_op_request_account_recoveries CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_request_account_recoveries ON sbds_op_request_account_recoveries CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_recover_accounts ON sbds_op_recover_accounts CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_recover_accounts ON sbds_op_recover_accounts CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_reset_accounts ON sbds_op_reset_accounts CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_reset_accounts ON sbds_op_reset_accounts CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_set_reset_accounts ON sbds_op_set_reset_accounts CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_set_reset_accounts ON sbds_op_set_reset_accounts CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_change_recovery_accounts ON sbds_op_change_recovery_accounts CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_change_recovery_accounts ON sbds_op_change_recovery_accounts CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_transfer_to_saving ON sbds_op_transfer_to_saving CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_transfer_to_saving ON sbds_op_transfer_to_saving CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_transfer_from_saving ON sbds_op_transfer_from_saving CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_transfer_from_saving ON sbds_op_transfer_from_saving CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_cancel_transfer_from_saving ON sbds_op_cancel_transfer_from_saving CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_cancel_transfer_from_saving ON sbds_op_cancel_transfer_from_saving CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_decline_voting_right ON sbds_op_decline_voting_right CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_decline_voting_right ON sbds_op_decline_voting_right CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_claim_reward_balances ON sbds_op_claim_reward_balances CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_claim_reward_balances ON sbds_op_claim_reward_balances CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_delegate_vesting_share ON sbds_op_delegate_vesting_share CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_delegate_vesting_share ON sbds_op_delegate_vesting_share CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_virtual_author_rewards ON sbds_op_virtual_author_rewards CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_virtual_author_rewards ON sbds_op_virtual_author_rewards CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_virtual_curation_rewards ON sbds_op_virtual_curation_rewards CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_virtual_curation_rewards ON sbds_op_virtual_curation_rewards CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_virtual_comment_rewards ON sbds_op_virtual_comment_rewards CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_virtual_comment_rewards ON sbds_op_virtual_comment_rewards CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_virtual_liquidity_rewards ON sbds_op_virtual_liquidity_rewards CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_virtual_liquidity_rewards ON sbds_op_virtual_liquidity_rewards CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_virtual_interests ON sbds_op_virtual_interests CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_virtual_interests ON sbds_op_virtual_interests CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_virtual_fill_convert_requests ON sbds_op_virtual_fill_convert_requests CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_virtual_fill_convert_requests ON sbds_op_virtual_fill_convert_requests CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_virtual_fill_vesting_withdraws ON sbds_op_virtual_fill_vesting_withdraws CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_virtual_fill_vesting_withdraws ON sbds_op_virtual_fill_vesting_withdraws CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_virtual_shutdown_witnesses ON sbds_op_virtual_shutdown_witnesses CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_virtual_shutdown_witnesses ON sbds_op_virtual_shutdown_witnesses CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_virtual_fill_orders ON sbds_op_virtual_fill_orders CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_virtual_fill_orders ON sbds_op_virtual_fill_orders CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_virtual_fill_transfer_from_saving ON sbds_op_virtual_fill_transfer_from_saving CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_virtual_fill_transfer_from_saving ON sbds_op_virtual_fill_transfer_from_saving CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_virtual_hardforks ON sbds_op_virtual_hardforks CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_virtual_hardforks ON sbds_op_virtual_hardforks CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_virtual_comment_payout_updates ON sbds_op_virtual_comment_payout_updates CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_virtual_comment_payout_updates ON sbds_op_virtual_comment_payout_updates CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_virtual_return_vesting_delegations ON sbds_op_virtual_return_vesting_delegations CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_virtual_return_vesting_delegations ON sbds_op_virtual_return_vesting_delegations CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_virtual_comment_benefactor_rewards ON sbds_op_virtual_comment_benefactor_rewards CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_virtual_comment_benefactor_rewards ON sbds_op_virtual_comment_benefactor_rewards CASCADE;',
    'DROP RULE IF EXISTS rule_update_sbds_op_virtual_producer_rewards ON sbds_op_virtual_producer_rewards CASCADE;',
    'DROP RULE IF EXISTS rule_delete_sbds_op_virtual_producer_rewards ON sbds_op_virtual_producer_rewards CASCADE;',
]


def create_rules():
    pass


def drop_rules():
    pass


CreateAllRule = create_rules()
DropRules = drop_rules()
